[provider]
cluster = "mainnet"
wallet = ""

[programs.localnet]
sla = "GUSxqUfUdqchfErA3DrW1jNVJKGdMpxt71AeDkJJtG5R"

[programs.devnet]
sla = "GUSxqUfUdqchfErA3DrW1jNVJKGdMpxt71AeDkJJtG5R"

[programs.mainnet]
sla = "GUSxqUfUdqchfErA3DrW1jNVJKGdMpxt71AeDkJJtG5R"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
