[provider]
cluster = "devnet"
wallet = "~/.config/solana/sla-treasury.json"

[programs.localnet]
sla_main = "2sochV4HLApPhUPHTYZstZDVdfkxQC1MUyrTVU6TSAxj"

[programs.devnet]
sla_main = "2sochV4HLApPhUPHTYZstZDVdfkxQC1MUyrTVU6TSAxj"

[programs.mainnet]
sla_main = "2sochV4HLApPhUPHTYZstZDVdfkxQC1MUyrTVU6TSAxj"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
