[programs.localnet]
sla_main = "2sochV4HLApPhUPHTYZstZDVdfkxQC1MUyrTVU6TSAxj"

[programs.devnet]
sla_main = "2sochV4HLApPhUPHTYZstZDVdfkxQC1MUyrTVU6TSAxj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/robin/.config/solana/sla-treasury.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
